version: "3"

services: 
    app:
        build: .
        env_file: 
            - ./.env
        volumes: 
            - ".:/usr/src"
            - "/usr/src/node_modules"
        ports: 
            - 5000:3000
        tty: true
        networks:
            - magento_sofianetwork
networks:
    magento_sofianetwork:
        external: true